/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ManipuladorPilhas;

public class App {

    public static void main(String[] args) {
        
        Pilha pilha = new Pilha(5);
        pilha.Empilhar(10);
        pilha.Empilhar(20);
        pilha.Empilhar(30);
        pilha.Empilhar(40);
        pilha.Empilhar(50);
        
        pilha.
        
       
        System.out.println(pilha.mostrarPilha());
        
        
    }
}
